version: '3.8'
services:
  database:
    container_name: postgres
    environment:
      POSTGRES_DB: java
      POSTGRES_PASSWORD: zaq1@WSX
      POSTGRES_USER: admin
    image: postgres:latest
    ports:
      - "5432:5432"